<?php
/**
 * V2AvailablePropertySuburbs
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Advertising Integration API
 *
 * The 'Advertising' integration focuses on allowing 3rd party systems and customized websites to sync available properties from Palace to display up-to-date advertising on a company's website.<BR><BR>The 'Advertising Integration' area does NOT require an upgrade from a 'Standard' API account to a 'Premium' API Account. There is a NO cost involved in using these contracts unless you are a 3rd Party solution provider wanting to integrate at a partner level.<BR><BR>The following is a list of contracts to integrate 'Available Properties' into a public website.  The first contract /v2AvailableProperties/JSON provides comprehensive array of currrent available properties with details.<BR><BR>  Every time the call is made to this contract it provides the current list at the time of the call.  If a property is no longer showing in the latest call that existed in previous calls you can use the /v2PreviousAvailableProperty/JSON/ contract to get information regarding the leased or withdrawn status and comments of the properties.<BR><BR> You can get a list of related images to a Property in Base64 encoded string (/v2AvailablePropertyImages/JSON) or a URL (/v2AvailablePropertyImagesURL/JSON/) directly to the JPG file.  Use the Base64 encoded option to download the images to your website<BR><BR> (NOTE: Do not use this contract to render images per request as the resulting request will be too slow to handle this).<BR><BR>  You can use the URL requests to link directly to your site.
 *
 * OpenAPI spec version: 2.0.0
 * Contact: development@getpalace.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * V2AvailablePropertySuburbs Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class V2AvailablePropertySuburbs implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'v2AvailablePropertySuburbs';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'property_suburb_code' => 'string',
        'property_suburb_district_or_postcode' => 'string',
        'property_suburb_name' => 'string',
        'property_suburb_region_or_state' => 'string',
        'property_suburb_type' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'property_suburb_code' => 'string',
        'property_suburb_district_or_postcode' => 'string',
        'property_suburb_name' => 'string',
        'property_suburb_region_or_state' => 'string',
        'property_suburb_type' => 'string'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'property_suburb_code' => 'PropertySuburbCode',
        'property_suburb_district_or_postcode' => 'PropertySuburbDistrictOrPostcode',
        'property_suburb_name' => 'PropertySuburbName',
        'property_suburb_region_or_state' => 'PropertySuburbRegionOrState',
        'property_suburb_type' => 'PropertySuburbType'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'property_suburb_code' => 'setPropertySuburbCode',
        'property_suburb_district_or_postcode' => 'setPropertySuburbDistrictOrPostcode',
        'property_suburb_name' => 'setPropertySuburbName',
        'property_suburb_region_or_state' => 'setPropertySuburbRegionOrState',
        'property_suburb_type' => 'setPropertySuburbType'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'property_suburb_code' => 'getPropertySuburbCode',
        'property_suburb_district_or_postcode' => 'getPropertySuburbDistrictOrPostcode',
        'property_suburb_name' => 'getPropertySuburbName',
        'property_suburb_region_or_state' => 'getPropertySuburbRegionOrState',
        'property_suburb_type' => 'getPropertySuburbType'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['property_suburb_code'] = isset($data['property_suburb_code']) ? $data['property_suburb_code'] : null;
        $this->container['property_suburb_district_or_postcode'] = isset($data['property_suburb_district_or_postcode']) ? $data['property_suburb_district_or_postcode'] : null;
        $this->container['property_suburb_name'] = isset($data['property_suburb_name']) ? $data['property_suburb_name'] : null;
        $this->container['property_suburb_region_or_state'] = isset($data['property_suburb_region_or_state']) ? $data['property_suburb_region_or_state'] : null;
        $this->container['property_suburb_type'] = isset($data['property_suburb_type']) ? $data['property_suburb_type'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets property_suburb_code
     *
     * @return string
     */
    public function getPropertySuburbCode()
    {
        return $this->container['property_suburb_code'];
    }

    /**
     * Sets property_suburb_code
     *
     * @param string $property_suburb_code External Code Reference (NOTE: Based to 'Suburb Type')
     *
     * @return $this
     */
    public function setPropertySuburbCode($property_suburb_code)
    {
        $this->container['property_suburb_code'] = $property_suburb_code;

        return $this;
    }

    /**
     * Gets property_suburb_district_or_postcode
     *
     * @return string
     */
    public function getPropertySuburbDistrictOrPostcode()
    {
        return $this->container['property_suburb_district_or_postcode'];
    }

    /**
     * Sets property_suburb_district_or_postcode
     *
     * @param string $property_suburb_district_or_postcode Suburb District (NOTE: In 'Australia' this displays a 'Post Code')
     *
     * @return $this
     */
    public function setPropertySuburbDistrictOrPostcode($property_suburb_district_or_postcode)
    {
        $this->container['property_suburb_district_or_postcode'] = $property_suburb_district_or_postcode;

        return $this;
    }

    /**
     * Gets property_suburb_name
     *
     * @return string
     */
    public function getPropertySuburbName()
    {
        return $this->container['property_suburb_name'];
    }

    /**
     * Sets property_suburb_name
     *
     * @param string $property_suburb_name Suburb Name.
     *
     * @return $this
     */
    public function setPropertySuburbName($property_suburb_name)
    {
        $this->container['property_suburb_name'] = $property_suburb_name;

        return $this;
    }

    /**
     * Gets property_suburb_region_or_state
     *
     * @return string
     */
    public function getPropertySuburbRegionOrState()
    {
        return $this->container['property_suburb_region_or_state'];
    }

    /**
     * Sets property_suburb_region_or_state
     *
     * @param string $property_suburb_region_or_state Region (NOTE: In 'Australia' this displays a 'State')
     *
     * @return $this
     */
    public function setPropertySuburbRegionOrState($property_suburb_region_or_state)
    {
        $this->container['property_suburb_region_or_state'] = $property_suburb_region_or_state;

        return $this;
    }

    /**
     * Gets property_suburb_type
     *
     * @return string
     */
    public function getPropertySuburbType()
    {
        return $this->container['property_suburb_type'];
    }

    /**
     * Sets property_suburb_type
     *
     * @param string $property_suburb_type The 'Suburb Type' is describes where the source of the suburb code originates
     *
     * @return $this
     */
    public function setPropertySuburbType($property_suburb_type)
    {
        $this->container['property_suburb_type'] = $property_suburb_type;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


